// generates fake users
exports.albums = [
  { id: 1, album_name: 'Utopia', artist_name: 'Travis Scott', release_date: '2020-11-30' },
  { id: 2, album_name: 'BE (Deluxe Edition)', artist_name: 'BTS', release_date: '2020-11-20' },
  { id: 3, album_name: 'After Hours', artist_name: 'The Weeknd', release_date: '2020-03-20' },
  { id: 4, album_name: 'Gold Mine', artist_name: 'Gabby Barett', release_date: '2020-06-19' },
  { id: 5, album_name: 'Discovery', artist_name: 'Daft Punk', release_date: '2001-02-26' },
  { id: 6, album_name: 'Damn', artist_name: 'Kendrick Lamar', release_date: '2017-04-14' },
  { id: 7, album_name: 'Father of Asahd', artist_name: 'DJ Khaled', release_date: '2019-05-17' },
  { id: 8, album_name: 'Classics', artist_name: 'Ratatat', release_date: '2006-08-22' },
  { id: 9, album_name: 'No tracks, no beats', artist_name: 'Emcee Hafiz', release_date: '2020-10-12' },
];

exports.songs = [
  { song_name: 'Franchise', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 1 },
  { song_name: 'Dynamite', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 2 },
  { song_name: 'Alone Again', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Too late', track_number: 2, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Hardest to Love', track_number: 3, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Scared to Live', track_number: 4, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Snowchild', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Escape from LA', track_number: 6, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Heartless', track_number: 7, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Faith', track_number: 8, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Blinding Lights', track_number: 9, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'In your Eyes', track_number: 10, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Save Your Tears', track_number: 11, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Repeat After Me', track_number: 12, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'After Hours', track_number: 13, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'Until I Bleed Out', track_number: 14, rating: Math.ceil(Math.random() * 5), album_id: 3 },
  { song_name: 'I Hope', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Thank God', track_number: 2, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Write It on My Heart', track_number: 3, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Footprints on the Moon', track_number: 4, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'You are the Only reason', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Goldmine', track_number: 6, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'The Good Ones', track_number: 7, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Jesus and My Mama', track_number: 8, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Hall of fame', track_number: 9, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Got Me', track_number: 10, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Rose needs a Jack', track_number: 11, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'Strong', track_number: 12, rating: Math.ceil(Math.random() * 5), album_id: 4 },
  { song_name: 'One More Time', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Aerodynamic', track_number: 2, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Digital Love', track_number: 3, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Harder, Better, Faster, Stronger', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Crescendolls', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Nightvision', track_number: 6, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Superheroes', track_number: 7, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'High Life', track_number: 8, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Something About Us', track_number: 9, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Voyager', track_number: 10, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Veridis Quo', track_number: 11, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Short Circuit', track_number: 12, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Face to Face', track_number: 13, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Too Long', track_number: 14, rating: Math.ceil(Math.random() * 5), album_id: 5 },
  { song_name: 'Blood', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'DNA', track_number: 2, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Yah', track_number: 3, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Element', track_number: 4, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Feel', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Loyalty', track_number: 6, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Pride', track_number: 7, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Humble', track_number: 8, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Lust', track_number: 9, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Love', track_number: 10, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'XXX', track_number: 11, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Fear', track_number: 12, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'God', track_number: 13, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Duckworth', track_number: 14, rating: Math.ceil(Math.random() * 5), album_id: 6 },
  { song_name: 'Holy Mountain', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Wish Wish', track_number: 2, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Jealeous', track_number: 3, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Just Us', track_number: 4, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'You Stay', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Celebrate', track_number: 6, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Higher', track_number: 7, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Won\"t take my soul', track_number: 8, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Weather the storm', track_number: 9, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Big Boy Talk', track_number: 10, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Freak n You', track_number: 11, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Top Off', track_number: 12, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'No Brainer', track_number: 13, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Thank You', track_number: 14, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Holy Ground', track_number: 15, rating: Math.ceil(Math.random() * 5), album_id: 7 },
  { song_name: 'Montanita', track_number: 1, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Lex', track_number: 2, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Gettysburg', track_number: 3, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Wildcat', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Tropicana', track_number: 5, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Loud Pipes', track_number: 6, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Nostrand', track_number: 7, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Swisha', track_number: 8, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Kennedy', track_number: 9, rating: Math.ceil(Math.random() * 5), album_id: 8 },
  { song_name: 'Tacobel Canon', track_number: 10, rating: Math.ceil(Math.random() * 5), album_id: 8 },
]